version: 2.1
machine:
  timezone: UTC
  java:
    version: oraclejdk11

orbs:
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-ecs: circleci/aws-ecs@0.0.8

defaults: &defaults
  working_directory: ~/closette
  docker:
    - image: circleci/node:10-stretch

deploy: &deploy
  <<: *defaults
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - aws-ecr/build-and-push-image:
        checkout: false
        account-url: AWS_ECR_ACCOUNT_URL
        aws-access-key-id: AWS_ACCESS_KEY_ID
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        repo: "${AWS_RESOURCE_NAME_PREFIX}-${AWS_RESOURCE_NAME_SUFFIX}"
        region: AWS_DEFAULT_REGION
        tag: "${CIRCLE_SHA1}"
        extra-build-args: --build-arg app_env="$APP_ENV" --build-arg auth0_client_id=${AUTH0_CLIENT_ID} --build-arg auth0_client_secret=${AUTH0_CLIENT_SECRET} --build-arg auth0_callback_url=${AUTH0_CALLBACK_URL} --build-arg auth0_domain=${AUTH0_DOMAIN} --build-arg auth0_audience=${AUTH0_AUDIENCE} --build-arg base_url=${BASE_URL} --build-arg express_session_secret=${EXPRESS_SESSION_SECRET} --build-arg sendgrid_apikey=${SENDGRID_APIKEY}
    - aws-ecs/update-service:
        family: "${AWS_RESOURCE_NAME_PREFIX}-service-${AWS_RESOURCE_NAME_SUFFIX}"
        cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster-${AWS_RESOURCE_NAME_SUFFIX}"
        container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service-${AWS_RESOURCE_NAME_SUFFIX},image-and-tag=${AWS_ECR_ACCOUNT_URL}/${AWS_RESOURCE_NAME_PREFIX}-${AWS_RESOURCE_NAME_SUFFIX}:${CIRCLE_SHA1}"
        verify-revision-is-deployed: true
    - run:
        name: Test the deployment
        command: curl -s --retry 10 $BASE_URL | grep "theCXN"

jobs:
  setup_environment:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v1-{{ .Branch }}-
            - npm-v1-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules/
          key: npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
  deploy-int:
    <<: *deploy
  deploy-stage:
    <<: *deploy
  deploy-sandbox:
    <<: *deploy
  deploy-prod:
    <<: *deploy

workflows:
  build_and_deploy:
    jobs:
      - setup_environment:
          filters:
            branches:
              only:
                - master
                - staging
                - production
                - sandbox
      - deploy-int:
          context: integration
          filters:
            branches:
              only:
                - master
          requires:
            - setup_environment
      - deploy-stage:
          context: staging
          filters:
            branches:
              only:
                - staging
          requires:
            - setup_environment
      - deploy-sandbox:
          context: sandbox
          filters:
            branches:
              only:
                - sandbox
          requires:
            - setup_environment
      - deploy-prod:
          context: production
          filters:
            branches:
              only:
                - production
          requires:
            - setup_environment